default_platform(:ios)

VERSION_NUMBER = ENV['VERSION_NUMBER']
BUILD_NUMBER = ENV['BUILD_NUMBER']
APPLE_SPECIAL_PASS = ENV['APPLE_SPECIAL_PASS']
APPLE_USERNAME = ENV['APPLE_USERNAME']

platform :ios do
  before_all do
    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "#{APPLE_SPECIAL_PASS}"
  end
  desc "Your App descriptin"
	lane :prod do
		disable_automatic_code_signing(
			  path: "YourProject.xcodeproj",
			  team_id: "your team id",
		)
		update_app_identifier(
			  xcodeproj: "YourProject.xcodeproj",
			  plist_path: "path to Info.plist",
			  app_identifier: "your app identifier"
		)
		update_project_provisioning(
			  xcodeproj: "YourProject.xcodeproj",
			  profile: "./.github/certs/app.mobileprovision",
			  code_signing_identity: "Your code signing identity",
			  build_configuration: "Release",
			  code_signing_identity: "iPhone Distribution"
	        )
		increment_version_number(
  			version_number: "#{VERSION_NUMBER}"
		)
		increment_build_number(
  			build_number: "#{BUILD_NUMBER}"
		)
 		build_ios_app(
			  workspace: "YourProject.xcworkspace",
			  configuration: "Release",
			  scheme: "your app scheme",
			  clean: true,
			  output_name: "app.ipa",
			  export_method: "app-store",
			  export_xcargs: "-allowProvisioningUpdates",
			  export_options: {
			    compileBitcode: true
			  }
 		)
		upload_to_testflight(
			  username: "#{APPLE_USERNAME}",
			  apple_id: "your Apple ID",
			  skip_submission: true,
			  skip_waiting_for_build_processing: true
		)
	end
end
